# Generated by Django 3.2 on 2024-01-22 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=uuid.uuid4, max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.IntegerField(choices=[(1, 'Completed'), (2, 'Rejected')], default=1)),
                ('paid_at', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_for_loan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_detail', to='loans.loan')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='payments.payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payments_loans_detail',
            field=models.ManyToManyField(related_name='payments_loans', to='payments.PaymentLoanDetail'),
        ),
    ]
