# docker-compose.yml

version: '3'

services:
  web:
    build: .
    #command: sh -c "python manage.py runserver 0.0.0.0:8000"
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "8000:8000"
