# Generated by Django 3.2 on 2024-01-22 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=uuid.uuid4, max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Rejected'), (4, 'Paid')], default=1)),
                ('paid_at', models.DateTimeField(null=True)),
                ('contract_version', models.CharField(max_length=30)),
                ('maximus_payment_date', models.DateTimeField(auto_now=True)),
                ('take_at', models.DateTimeField(null=True)),
                ('customer_external', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_loan', to='customers.customer')),
            ],
        ),
    ]
